#Border Colors
source = ~/.cache/wal/colors-hyprland.conf
general {
    gaps_in = 5
    gaps_out = 15

    border_size = 2

    # https://wiki.hypr.land/Configuring/Variables/#variable-types for info about colors
    col.active_border = $color1 $color4 $color3 45deg
    col.inactive_border = $background

    # Set to true enable resizing windows by clicking and dragging on borders and gaps
    resize_on_border = false

    # Please see https://wiki.hypr.land/Configuring/Tearing/ before you turn this on
    allow_tearing = false

    layout = dwindle
}


