#################
### AUTOSTART ###
#################

exec-once = waybar && hypridle && dunst
exec-once = hypridle
exec-once = dunst
exec-once = sleep 1 && waypaper --restore && sleep 0.5 && wal -R
exec-once = /usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1
